# Generated by Django 4.2.29 on 2026-03-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
